# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1upYqSinPEgcdMS0Mj0NjBrUIuBvTUpZt
"""

idade_renata = 14
idade_fabiana = 18
dinheiro_iara = 5000.00
if (idade_renata >= 14 and idade_fabiana == 18 or dinheiro_iara == 5000.00 ):
    situação = 'vai viajar'
else:
    situação = 'não vai viajar'
print (f'rodrigo {situação} para Portugal')

sabeSambar = 'sim'
gostaFeijoada = 'não'
torceSelecaoBrasileira = 'sim'
if (sabeSambar == 'sim' or gostaFeijoada == 'sim' and torceSelecaoBrasileira == 'sim'):
    print('esse é brasileiro')
else:
    print('esse não é brasileiro')

temDentes = 'sim'
temFome = 'sim'
gosta = 'sim'

if temDentes == 'sim':
    TDcondicao = 'verdadeiro'
elif temDentes == 'não':
    TDcondicao = 'falso'

if temFome == 'sim':
    TFcondicao = 'verdadeiro'
elif temFome == 'não':
    TFcondicao = 'falso'

if gosta == 'sim':
    Gcondicao = 'verdadeiro'
elif gosta == 'não':
    Gcondicao = 'falso'

if Gcondicao == 'falso' or TFcondicao == 'falso':
    GTFcondicao = 'falso'
else:
    GTFcondicao = 'verdadeiro'

if GTFcondicao == 'verdadeiro' and TDcondicao == 'verdadeiro':
    Fcondicao = 'verdadeiro'
else:
    Fcondicao = 'falso'

print(f'A pessoa precisa ter dentes R: {TDcondicao}, e ter fome R: {TFcondicao}, ou gostar de maçã R: {Gcondicao} = Resposta final: {Fcondicao}')